### ISSUE TITLE
Dependent on nodes that don't exist

### ISSUE THREAD

**Issue by bcrethers** [gkpalomo/CSE360project#5]
If we enter a series of tasks with dependencies, there is no check to make sure of the dependent tasks exists.

**Comment by gkpalomo** [comment]
Fixed in latest patch: 
`for (Project proj : projectList) {
						dependencyFlag = false;
						for (String dependency : proj.getProjDependencies().split(",")) {
							if (dependency.equals("")) {
								startNode = edgeList.size();
								dependencyFlag = true;
							}
							for (int j = 0; j < projectList.size(); j++) {
								if (dependency.equals(projectList.get(j).getProjTitle()))
									dependencyFlag = true;
							}
							if (!dependencyFlag) {
								errorLabel.setText("Non-existent dependency detected");
								return;
							}

							Edge edge = new Edge();
							edge.setEdge(dependency, proj.getProjTitle(), proj.getProjDuration());
							edgeList.add(edge);
						}
					}`
